PreCommit:
  ALL:
    exclude:
      - '_spec/**/**'

  AuthorName:
    enabled: false

  AuthorEmail:
    enabled: false

  HardTabs:
    enabled: true

  TrailingWhitespace:
    enabled: true

  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true
    on_warn: fail
    command: ['bundle', 'exec', 'rubocop']
